import forms from "@tailwindcss/forms";

/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "primary-fixed": "#b1ecf8",
        "on-primary-container": "#8fc9d5",
        "surface-bright": "#f8f9fa",
        error: "#ba1a1a",
        "on-secondary-fixed-variant": "#3f465c",
        "on-surface-variant": "#40484a",
        "on-secondary-container": "#5c647a",
        "surface-container-highest": "#e1e3e3",
        "on-secondary": "#ffffff",
        secondary: "#565e74",
        primary: "#003e46",
        "primary-fixed-dim": "#96d0db",
        "secondary-fixed-dim": "#bec6e0",
        surface: "#f8f9fa",
        background: "#f8f9fa",
        "primary-container": "#145660",
        "on-background": "#191c1d",
        "surface-variant": "#e1e3e3",
        "inverse-surface": "#2e3131",
        "on-primary-fixed": "#001f24",
        outline: "#70797a",
        "surface-tint": "#2a6671",
        "on-tertiary-fixed": "#2f1400",
        "on-tertiary-fixed-variant": "#673d19",
        "inverse-primary": "#96d0db",
        "on-tertiary": "#ffffff",
        "error-container": "#ffdad6",
        "secondary-container": "#dae2fd",
        "on-primary": "#ffffff",
        "inverse-on-surface": "#eff1f1",
        "surface-container": "#edeeee",
        "surface-dim": "#d9dadb",
        "on-secondary-fixed": "#131b2e",
        "on-primary-fixed-variant": "#054e58",
        "outline-variant": "#bfc8ca",
        "on-error-container": "#93000a",
        "surface-container-high": "#e7e8e9",
        "surface-container-low": "#f2f4f4",
        "surface-container-lowest": "#ffffff",
        tertiary: "#552e0b",
        "on-error": "#ffffff",
        "secondary-fixed": "#dae2fd",
        "on-tertiary-container": "#f1b386",
        "tertiary-fixed-dim": "#f8b98c",
        "tertiary-fixed": "#ffdcc4",
        "on-surface": "#191c1d",
        "tertiary-container": "#704420",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        sm: "0.5rem",
        gutter: "1.5rem",
        "2xl": "3rem",
        unit: "4px",
        xl: "2rem",
        margin: "2rem",
        md: "1rem",
        xs: "0.25rem",
        lg: "1.5rem",
      },
      fontFamily: {
        inter: ["Inter", "system-ui", "sans-serif"],
        h1: ["Inter", "sans-serif"],
        h3: ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "label-caps": ["Inter", "sans-serif"],
        h2: ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "system-id": ["ui-monospace", "monospace"],
      },
      fontSize: {
        h1: [
          "2.25rem",
          {
            lineHeight: "2.75rem",
            letterSpacing: "-0.02em",
            fontWeight: "700",
          },
        ],
        h3: [
          "1.5rem",
          {
            lineHeight: "2rem",
            letterSpacing: "-0.01em",
            fontWeight: "600",
          },
        ],
        "body-md": ["1rem", { lineHeight: "1.5rem", fontWeight: "400" }],
        "body-lg": ["1.125rem", { lineHeight: "1.75rem", fontWeight: "400" }],
        "label-caps": [
          "0.75rem",
          {
            lineHeight: "1rem",
            letterSpacing: "0.05em",
            fontWeight: "600",
          },
        ],
        h2: [
          "1.875rem",
          {
            lineHeight: "2.25rem",
            letterSpacing: "-0.01em",
            fontWeight: "600",
          },
        ],
        "body-sm": ["0.875rem", { lineHeight: "1.25rem", fontWeight: "400" }],
        "system-id": ["0.875rem", { lineHeight: "1.25rem", fontWeight: "500" }],
      },
    },
  },
  plugins: [forms],
};
